"""initial tables

Revision ID: 56107aed2149
Revises: 
Create Date: 2023-09-27 09:45:04.322134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56107aed2149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('artist_image_large_path', sa.String(), nullable=False),
    sa.Column('artist_image_medium_path', sa.String(), nullable=True),
    sa.Column('artist_image_small_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist'),
    sa.UniqueConstraint('artist_image_large_path'),
    sa.UniqueConstraint('artist_image_medium_path'),
    sa.UniqueConstraint('artist_image_small_path'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('vocals_path', sa.String(), nullable=False),
    sa.Column('accompaniments_path', sa.String(), nullable=False),
    sa.Column('text_path', sa.String(), nullable=False),
    sa.Column('total_listeners', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accompaniments_path'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('text_path'),
    sa.UniqueConstraint('vocals_path')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('song_id', sa.UUID(), nullable=True),
    sa.Column('listen_count', sa.Integer(), nullable=False),
    sa.Column('listened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('songs')
    op.drop_table('users')
    op.drop_table('artists')
    # ### end Alembic commands ###
