"""added song length

Revision ID: c8d1c9124649
Revises: a9102fdd839f
Create Date: 2023-08-28 20:00:14.434212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d1c9124649'
down_revision = 'a9102fdd839f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('length', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'length')
    # ### end Alembic commands ###
