"""added user profile name

Revision ID: d002785a2f14
Revises: dd8cb2d5d7d1
Create Date: 2023-05-14 22:46:53.677487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd002785a2f14'
down_revision = 'dd8cb2d5d7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('profile_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_name')
    op.alter_column('songs', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
