"""added relationship between songs and artists

Revision ID: dd8cb2d5d7d1
Revises: fdc5f41fdcff
Create Date: 2023-05-12 18:34:52.998252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8cb2d5d7d1'
down_revision = 'fdc5f41fdcff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
